# Endpoints
simple_rest_adapter_endpoints:
    resource: 'routing/endpoints.yml'
    prefix: /pimcore-datahub-webservices/simplerest/{config}

# Swagger
simple_rest_adapter_swagger:
    resource: 'routing/swagger.yml'
    prefix: /pimcore-datahub-webservices/simplerest
